In [2]:
import numpy as np

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

8

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [9]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [10]:
arr[0:5] = 100

In [11]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
slice_of_arr = arr[0:6]

In [13]:
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [14]:
slice_of_arr[:] = 99

In [15]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [16]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [17]:
arr_copy = arr.copy()

In [18]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
arr_copy[:] = 100

In [20]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [21]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [22]:
hend = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [23]:
hend[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
randnt = np.random.randint(0,100,10)

In [25]:
randnt

array([82, 43, 55, 99, 84, 74, 61, 99, 77, 12])

In [26]:
randnt.max

<function ndarray.max>

In [27]:
randnt.max()

99

In [28]:
randnt.argmax

<function ndarray.argmax>

In [29]:
randnt

array([82, 43, 55, 99, 84, 74, 61, 99, 77, 12])

In [30]:
randnt.argmax()

3