In [2]:
import numpy as np

In [15]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [17]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [18]:
arr_2d[0][2]

15

In [19]:
arr_2d[2,2]

45

In [30]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [45]:
arr_2d[1:, :2]

array([[20, 25],
       [35, 40]])

In [47]:
arr = np.arange(1,11)

In [49]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
bool_arr = arr > 5

In [52]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [55]:
arr_2d = np.arange(50).reshape(5,10)

In [56]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [62]:
arr_2d[1:3, 6:10]

array([[16, 17, 18, 19],
       [26, 27, 28, 29]])