In [10]:
import numpy as np

In [15]:
kalitiga = np.array([[1,2,3],[4,5,6],[7,8,9]]) * 3

In [17]:
kalitiga

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [29]:
c = np.random.randint(0,10,20).reshape(4,5)

In [30]:
c

array([[7, 0, 6, 0, 9],
       [9, 7, 6, 9, 2],
       [4, 2, 2, 9, 2],
       [2, 6, 5, 2, 7]])

In [32]:
np.linspace(0,10,40)

array([ 0.        ,  0.25641026,  0.51282051,  0.76923077,  1.02564103,
        1.28205128,  1.53846154,  1.79487179,  2.05128205,  2.30769231,
        2.56410256,  2.82051282,  3.07692308,  3.33333333,  3.58974359,
        3.84615385,  4.1025641 ,  4.35897436,  4.61538462,  4.87179487,
        5.12820513,  5.38461538,  5.64102564,  5.8974359 ,  6.15384615,
        6.41025641,  6.66666667,  6.92307692,  7.17948718,  7.43589744,
        7.69230769,  7.94871795,  8.20512821,  8.46153846,  8.71794872,
        8.97435897,  9.23076923,  9.48717949,  9.74358974, 10.        ])