In [12]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_may = [[1,2,3], [4,5,6], [7,8,9]]

In [7]:
np.array(my_may)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# np.arange() 

In [13]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.random.rand(5)

array([0.63988491, 0.25361333, 0.08329152, 0.63770668, 0.41767988])

In [25]:
np.random.randn(2)

array([-0.13954752, -0.62320784])

In [26]:
np.random.randint(1,100,10)

array([53, 79, 83, 24, 11, 98, 62,  1, 40, 76])

In [27]:
arr = np.arange(25)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr =  np.random.randint(0,50,10)

In [47]:
ranarr

array([17, 34, 18, 19, 46, 32,  0, 42, 45,  6])

In [50]:
max = np.arange(1,101).reshape(10,10)

In [52]:
max

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [58]:
np.linspace(1,51).reshape(2,2)

ValueError: cannot reshape array of size 50 into shape (2,2)